[package]
name = "feathered-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "feathered"
path = "src/main.rs"

[dependencies]
feathered-packs.workspace = true
serde_json.workspace = true
dirs = "6"
feathered-client.workspace = true
feathered-renderer.workspace = true
feathered-chunk.workspace = true
feathered-world.workspace = true
feathered-assets.workspace = true
pollster.workspace = true
